character_races = [
    "Hill Dwarf",
    "Mountain Dwarf",
    "High Elf",
    "Wood Elf",
    "Dark Elf (Drow)",
    "Lightfoot Halfling",
    "Stout Halfling",
    "Calishite (Human)",
    "Chondathan (Human)",
    "Damaran (Human)",
    "Illuskan (Human)",
    "Mulan (Human)",
    "Rashemi (Human)",
    "Shou (Human)",
    "Tethyrian (Human)",
    "Turami (Human)",
    "Dragonborn",
    "Forest Gnome",
    "Rock Gnome",
    "Half-Elf",
    "Half-Orc",
    "Tiefling"
]


character_classes = [
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
]