character_races = [
    "Hill Dwarf",
    "Mountain Dwarf",
    "High Elf",
    "Wood Elf",
    "Dark Elf (Drow)",
    "Lightfoot Halfling",
    "Stout Halfling",
    "Calishite",
    "Chondathan",
    "Damaran",
    "Illuskan",
    "Mulan",
    "Rashemi",
    "Shou",
    "Tethyrian",
    "Turami",
    "Dragonborn",
    "Forest Gnome",
    "Rock Gnome",
    "Half-Elf",
    "Half-Orc",
    "Tiefling"
]
